apiVersion: v1
kind: Pod
metadata:
  name: pong
  namespace: default
  labels:
    devops.app: pong
spec:
  containers:
    - image: python-test
      imagePullPolicy: IfNotPresent
      name: pong
      ports:
        - containerPort: 8000
          name: pong
          protocol: TCP
      env:
        - name: HOSTNAME
          value: pong

