apiVersion: v1
kind: Service
metadata:
  name: ping
  namespace: default
spec:
  selector:
    devops.app: ping
  ports:
    - protocol: TCP
      port: 8080
      name: ping
      targetPort: ping # 8000
      # nodePort: 30001
  # type: NodePort
  type: ClusterIP
  # type: LoadBalancer -> https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/nlb/
---
apiVersion: v1
kind: Service
metadata:
  name: external-ping
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: ping.default.svc.cluster.local